services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.wsgi:application --chdir backend"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DATABASE_URL
        sync: false
    staticPublishPath: backend/staticfiles 