# Generated by Django 5.2.4 on 2025-07-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
